### ISSUE TITLE
建立超級管理員

### ISSUE THREAD

**Issue by fruitcake0525** [railstaichung/rails-taichung#18]
基本功能上線後，
建立超級管理員後台，
有最高權限修正/刪除資料。

**Comment by fruitcake0525** [comment]
可以用類似namespace的方式，把active admin 的CSS分離
http://webmurmur.net/activeadmin-foundation/

**Comment by leo424y** [comment]
已解，使用ihower建議方式 http://bit.ly/2di5aqD
