### ISSUE TITLE
rails-taichung 起飛啦! 變現變現!

### ISSUE THREAD

**Issue by leo424y** [railstaichung/rails-taichung#2]
https://github.com/fruitcake0525/ror_taichung/issues/26

fruitcake0525 commented 4 days ago
單篇知識文章 (donate，紅包形式，Show Muscle)
連載知識文章 (訂閱制，連續高品質創作難!)
舉辦線下活動 (門票)
職缺看板 (引流量，掛GoogleAD廣告?)
媒合各種合作機會 (UserInfo的各種技能、作品集展示、跨領域)
所需技術:
1. 金流串接!

koei1025 commented 4 days ago
6.會員在提問題時免費，但是有急迫性的或沒人解決時，可以發出懸賞金吸引高手解題，平台抽懸賞金的10%，解題者得90%

**Comment by fruitcake0525** [comment]
變現參考
Rails教學 http://eggman.tv/
專欄 https://www.igetget.com/
文章 http://www.jianshu.com/
活動 https://www.accupass.com/ https://kktix.com/

**Comment by leo424y** [comment]
✨ ✨ Looks good 👍 ✨ ✨ 
專欄
http://weekly.codetengu.com/ 碼天狗週刊
https://wanqu.co/ 灣區日報

**Comment by fruitcake0525** [comment]
目前開發進度已經遇到高原期
站在選擇十字路口上 a.) 用專案繼續練功 b.) 開始定義使用者
b-1 : 面相 Rails初心者(教學、求職)
b-2 : 面相 Rails高高手(工作媒合、求職)
b-3 : 面相 所有Code工程師(社群活動、技術週報、月刊、翻譯文章)

**Comment by leo424y** [comment]
b-1，推廣Rails任務。加入專案後發現，強者越來越強，我認為自己還跟不上強者的腳步，社群推廣的認務想交給強者的風範。
b-2/b-3，應用Rails/資訊人才任務。我認為可行，若將人才建立資料庫，並依屬性提供適當資訊。
諸如線下教學、社群活動、技術週報、月刊、翻譯文章，會是條可發展之道。
執行的首要任務為，令人才主動登錄其「屬性」，其內容誘因需請大家共同激盪
接著依人才屬性轉化平台價值

**Comment by koei1025** [comment]
對於官網第1階段的開發已經接近尾聲(雖然還有很多bug要解XD)，接下來我認為重心應該放在推廣上，除了增加流量外，更重要的是得到使用者反饋。因此在如何推廣的作法上，我認為有主動與被動兩種方式，
1. 主動推廣：可以在Ruby相關粉絲團上發文宣傳外，也可以適時的投放廣告，另外一個技術型網站是否可以吸引流量的重要因素，不外乎這個網站要有**牛人**存在，我們都自認自己還有很多的學習空間，稱不上牛，目前認識最牛的也就是xdite，但是不要忘了在12/2~3舉辦的Ruby Conf就是一群牛人的聚會，有台灣牛、日本牛、美國牛、印度牛，我認為那是宣傳官網(抓牛)的大好時機，因此在12/2之前我們的官網必須要ready到一定程度。
2. 被動推廣：一個技術型網站要吸引流量除了牛人駐點外的另一個重要因素就是要有牛肉了( @Steven-Lin-Go 你負責的那部份就是放牛肉的鉆版了)，因此我認同舉辦線上/下教學、自辦hackathon、翻譯技術文章的作法，可以先從翻譯技術文章開始，也可以增強自己閱讀原文文章與presentation技巧

**Comment by iigmir** [comment]
官網關閉，關閉此 issue。
