### ISSUE TITLE
What the Disqus !

### ISSUE THREAD

**Issue by leo424y** [railstaichung/rails-taichung#25]
@Steven-Lin-Go  在 app/views/beefs/show.html.erb 下加入了 Disqus 的 Universal code 想使用他的留言功能，xn--rails-taichung-fr7v37nj2ji71am18diu4c27fll8b.com(雖然 universal code 內的網址格式有被產生器改過)。
但留言功能始終無法出現，可以請各位幫忙測看看嗎？
感謝！！

**Comment by koei1025** [comment]
Disqus我有建立一個partial，放在app/views/common/下，有需要的可以直接引用到view裡即可

**Comment by leo424y** [comment]
感謝Kenny熱情partial~
