### ISSUE TITLE
Sidekiq沒有正常運作

### ISSUE THREAD

**Issue by koei1025** [railstaichung/rails-taichung#33]
經過在Production的Console測試，是可以正常發信，因此確定問題是Sidekiq沒有正常work造成，要檢查production相關的設定

**Comment by leo424y** [comment]
redis 已裝好，production部分我今天檢查~~感謝回報

**Comment by leo424y** [comment]
阿哈，發現這個，https://github.com/seuros/capistrano-sidekiq 我來裝，裝了應該就能跑了~
