### ISSUE TITLE
活動頁面ckeditor編寫的內容有顯示問題

### ISSUE THREAD

**Issue by koei1025** [railstaichung/rails-taichung#45]
活動頁面ckeditor編寫的內容只會部份顯示，像是連結或icon可以正常顯示，但字體大小卻沒有生效

**Comment by fruitcake0525** [comment]
不知道是不是白名單的問題?
要再查一下
Imgur的外掛按鈕失蹤了!?

**Comment by iigmir** [comment]
官網關閉，關閉此 issue。
