### ISSUE TITLE
連不上 http://rails-taichung.com

### ISSUE THREAD

**Issue by caasi** [railstaichung/rails-taichung#58]
連不上 http://rails-taichung.com ，只看到 heroku 説： "There's nothing here, yet."

**Comment by koei1025** [comment]
官網因為使用率極低，所以索性關站了，資源目前集中在[FB社團](https://www.facebook.com/groups/RORTaichung)，社群仍每週四定時聚會，歡迎加入

**Comment by iigmir** [comment]
一、二、三、四、五、六、七、八、九、十。
謝謝大家，請坐。

我要不要順便把還在開的 issue 全部關閉？
